app/views/main.py
from flask import Blueprint, render_template, current_app
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from app.forms import MovieForm
from app.models import Movies

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def index():
    form = MovieForm
    movie = Movies.query.filter()
    return render_template('main/index.html', form=form, posts=movie)


@main.route('/jiami/')
def jiami():
    return generate_password_hash('123456')


@main.route('/check/<password>')
def check(password):
    if check_password_hash(
            'pbkdf2:sha256:50000$Tx7XTa0Q$13b274957198b1e5950f0fb065844c427167f2995b0cf4e80c1ff19177520727',
            password):
        return '密码正确'
    else:
        return '密码错误'


@main.route('/generate_token/')
def generate_token():
    s = Serializer(current_app.config['SECRET_KEY'], expires_in=3600)
    return s.dumps({'id': 250})


@main.route('/activate/<token>')
def activate(token):
    s = Serializer(current_app.config['SECRET_KEY'])
    try:
        data = s.loads(token)
    except:
        return 'token有误'
    return str(data.get('id'))

app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, request
from app.forms import RegisterForm, LoginForm, PasswordForm, IconForm
from app.email import send_mail
from app.models import User
from app.extensions import db, photos
from flask_login import login_user, logout_user, login_required, current_user
import os
from PIL import Image

user = Blueprint('user', __name__)


@user.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        u = User(username=form.username.data, password=form.password.data, email=form.email.data)
        db.session.add(u)
        db.session.commit()
        token = u.generate_activate_token()
        send_mail(form.email.data, '账户激活', 'email/account_activate', token=token,
                  username=form.username.data)
        flash('激活邮件已发送，请点击链接完成用户激活')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


@user.route('/activate/<token>')
def activate(token):
    if User.check_activate_token(token):
        flash('账户激活成功')
        return redirect(url_for('user.login'))
    else:
        flash('账户激活失败')
        return redirect(url_for('main.index'))


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if u is None:
            flash('无效的用户名')
        elif u.verify_password(form.password.data):
            login_user(u, remember=form.remember_me.data)

            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash('无效的密码')
    return render_template('user/login.html', form=form)


@user.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('您已退出登录')
    return redirect(url_for('main.index'))


@user.route('/profile/')
def profile():
    return render_template('user/profile.html')


@user.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_pwd.data):
            current_user.password = form.new_pwd.data
            db.session.add(current_user)
            flash('密码修改成功,下次请使用新密码登陆')
            return redirect('main.index')
        else:
            flash('无效的原始密码')
            return redirect('user.change_password')
    return render_template('user/change_password.html', form=form)


@user.route('/change_icon/', methods=['GET', 'POST'])
@login_required
def change_icon():
    form = IconForm()
    if form.validate_on_submit():

        suffix = os.path.splitext(form.icon.data.filename)[1]
        name = rand_str() + suffix
        photos.save(form.icon.data, name=name)
        pathname = os.path.join(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], name))
        img = Image.open(pathname)
        img.thumbnail((64, 64))
        img.save(pathname)
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], current_user.icon))
        current_user.icon = name
        db.session.add(current_user)
        flash('头像已更换')
    return render_template('user/change_icon.html', form=form)


def rand_str(length=32):
    import random
    base_str = 'abcdefghijklmnopqrstuvwxyz1234567890'
    return ''.join(random.choice(base_str) for i in range(length))

app/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}?电影{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse navbar-static-top" style="border-radius: 0px">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="collapse navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">?电影</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">最新</a></li>
{#                    <li><a href="#">模板2</a></li>#}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('user.logout') }}">退出</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">{{ current_user.username }}<span
                                    class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('user.profile') }}">个人信息</a></li>
                                <li><a href="{{ url_for('user.change_password') }}">修改密码</a></li>
                                <li><a href="{{url_for('user.change_icon')}}">修改头像</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ url_for('user.login') }}">登陆</a></li>
                        <li><a href="{{ url_for('user.register') }}">注册</a></li>
                    {% endif %}
                    </ul>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

{% endblock %}

{% block content %}
    <div class="container">
        {# get_flashed_messages获取所有的flash消息 #}
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible"
                 role="alert">
                <button type="button" class="close"
                        data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}默认内容{% endblock %}
    </div>

{% endblock %}